spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123654147a
      url: jdbc:mysql://localhost/springcloud_sell?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  devlala
